### ISSUE TITLE
the problem of realizing the test13[Random number sequence, 64-bit]

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#10]
test13[Random number sequence, 64-bit]
 this test is aiming to read and write 64bit  of data at a time from the RAM. 
this test13 is same to test9[random number sequence,32-bit]
the code of realizing the test13 is as following:
void movinvr_64_bit(long me)
{
		long i, j, done;
		ulong seed1, seed2;
		ulong *p;
		ulong *pe;
		ulong *start,*end;
		ulong num0,num1,bad;//ulong: 8-bytes length under 64-bit compiler. 4-bytes length under 32-bit compiler.
	
		/* Initialize memory with initial sequence of random numbers.  */
		if (cpu_id.fid.bits.rdtsc) {
			asm __volatile__ ("rdtsc":"=a" (seed1),"=d" (seed2));
		} else {
			seed1 = 521288629 + v->pass;
			seed2 = 362436069 - v->pass;
		}
	 
		/* Display the current seed */
			if (mstr_cpu == me) hprint(LINE_PAT, COL_PAT, seed1);
			
		rand_seed_64_bits(seed1, seed2, me);
		for (j=0; j<segs; j++) {
			calculate_chunk(&start, &end, me, j, 4);
			pe = start;
			p =  start;
			done = 0;
			do {
				do_tick(me);
				BAILR
	
				/* Check for overflow */
				if (pe + SPINSZ > pe && pe != 0) {
					pe += SPINSZ;
				} else {
					pe = end;
				}
				if (pe >= end) {
					pe = end;
					done++;
				}
				if (p >= pe ) {
					break;
				}
	/* Original C code replaced with hand tuned assembly code */
#if 1			
				*p = (rand_64_bits(me)&0xffffffff);
				*(++p) = (rand_64_bits(me)>>32);//高位地址高字节，little-endian
				--p;
				for (; p < pe; ) {
					p+=2;
					*p = (rand_64_bits(me)&0xffffffff);
					*(++p) = (rand_64_bits(me)>>32);
					--p;
				}
#else
				*p=rand_64_bits(me);
				for (; p < pe; ) {
					p++;
					*p=rand_64_bits(me);
				}
	
#endif
	 
				p = pe + 1;
			} while (!done);
		}
	
		/* Do moving inversions test. Check for initial pattern and then
		 * write the complement for each memory location.
		 */
		for (i=0; i<2; i++) {
			rand_seed_64_bits(seed1, seed2, me);
			for (j=0; j<segs; j++) {
				calculate_chunk(&start, &end, me, j, 4);
				pe =start;
				p = start;
				done = 0;
				do {
					do_tick(me);
					BAILR
	
					/* Check for overflow */
					if (pe + SPINSZ > pe && pe != 0) {
						pe += SPINSZ;
					} else {
						pe = end;
					}
					if (pe >= end) {
						pe = end;
						done++;
					}
					if (p >= pe ) {
						break;
					}
	/* Original C code replaced with hand tuned assembly code */
#if  1			
					num1=(rand_64_bits(me)>>32);
					num0 =(rand_64_bits(me)&0xffffffff);
					if (i) {
							num1 = ~num1;
							num0 = ~num0;
					}
					if ((bad=*p) != num0 ) {
							error((ulong*)p, num0, bad);
					}
					if ((bad=*(++p)) != num1 ) {
							error((ulong*)p, num1, bad);
							--p;
					}
					*p = ~num0;
					*(++p) = ~num1;
					--p;
		
					for (; p < pe; ) {
						p+=2;
						num1=(rand_64_bits(me)>>32);
						num0 =(rand_64_bits(me)&0xffffffff);
						if (i) {
								num1 = ~num1;
								num0 = ~num0;
						}
						if ((bad=*p) != num0 ) {
								error((ulong*)p, num0, bad);
						}
						if ((bad=*(++p)) != num1) {
								error((ulong*)p, num1, bad);
								--p;
						}
						*p = ~num0;
						*(++p) = ~num1;
						--p;
					}
#else
					num=rand_64_bits(me);
					if (i) {
							num = ~num;
					}
					if ((bad=*p) != num ) {
							error_64bits(p, num, bad);
					}
					*p = ~num;
		
					for (; p < pe; ) {
						p++;
						num=rand_64_bits(me);
						if (i) {
							num = ~num;
						}
						if ((bad=*p) != num ) {
							error_64bits(p, num, bad);
						}
						*p = ~num;
					}
					
#endif									
					p = pe + 1;
				} while (!done);
			}
		}
	
		

when I run the execute binary file, the screen is filled with error report.		
}

**Comment by tommybreak** [comment]
do u have any suggestions?

**Comment by anphsw** [comment]
Can you make a properly formatted commit so I can test it?
