### ISSUE TITLE
the problem on change_timing_xxx

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#11]
have you try to realize the function about changing timing of  "HSW IMC"?
in the extra.c , no function is silimar to "0xFFFF, 0x0007, "HSW IMC" or any other "Integrated Memory Controllers".

**Comment by anphsw** [comment]
It's possible to add such support if:
1. interface exists (8086:0c00 or 8086:0a04) at boot time (for example, some bios'es don't enable it at boot time)
2. It's documented. (I searched on intel site, but found no info how to change IMC timings)
If you know links for such documents or info, let me know.

**Comment by tommybreak** [comment]
I have MRC of  ""IVB IMC"", if you want , I can share it with you.

**Comment by tommybreak** [comment]
MRC: Memory Reference Code

**Comment by anphsw** [comment]
Just put links to documents here.

**Comment by tommybreak** [comment]
Could you tell your e-mail to me?

**Comment by anphsw** [comment]
sysop@880.ru
