### ISSUE TITLE
question about "static void poll_fsb_nhm(void){xxxxxxxxx}"

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#12]
my moterboard is ASUS Z370-A and its memory type is DDR4.
the CPU is i5-8400, the memory controller is "INTEL IMC (Integrated Memory Controllers)" whose vendor is 0xffff and device is 0x0001.
when the memtest86 is executed, "RAM:   0  MHZ" is displayed on the 8th line of the screen.
It's confirmed that  the funtion,"static void poll_fsb_nhm(void){xxxxxxxxx}" cannot poll the memory frequency.
do you have any suggestion?

**Comment by anphsw** [comment]
It seems like a buggy BIOS or so. Vendor ID and device id contain invalid values which indicates that device is not properly configured. At least vendor ID must be 8086 (Intel) to operate correctly and try to make some fixes.

**Comment by tommybreak** [comment]
/* INTEL IMC (Integrated Memory Controllers) */
	{ 0xFFFF, 0x0001, "Core IMC","", 	 				0, poll_fsb_nhm, 	poll_timings_nhm, set_timings_nhm,setup_nhm, poll_nothing},
	{ 0xFFFF, 0x0002, "Core IMC","", 	 				0, poll_fsb_nhm32, 	poll_timings_nhm, set_timings_nhm,setup_nhm32, poll_nothing},
	{ 0xFFFF, 0x0003, "Core IMC","", 	 				0, poll_fsb_wmr, 	poll_timings_wmr, set_timings,setup_wmr, poll_nothing},
	{ 0xFFFF, 0x0004, "SNB IMC","", 	 				0, poll_fsb_snb, 	poll_timings_snb, set_timings,setup_wmr, poll_nothing},
	{ 0xFFFF, 0x0005, "SNB-E IMC","",		 	 		0, poll_fsb_snbe, poll_timings_snbe, set_timings,setup_wmr, poll_nothing},
	{ 0xFFFF, 0x0006, "IVB IMC","",			 	 		0, poll_fsb_ivb, 	poll_timings_snb, set_timings,setup_wmr, poll_nothing},
	{ 0xFFFF, 0x0007, "HSW IMC","",			 	 		0, poll_fsb_ivb, 	poll_timings_hsw, set_timings_hsw,setup_wmr, poll_nothing},		
	{ 0xFFFF, 0x0008, "PineView IMC","", 			0, poll_fsb_p35, poll_timings_p35, set_timings,setup_p35, poll_nothing},
	{ 0xFFFF, 0x0009, "CedarTrail IMC","",		0, poll_fsb_ct, poll_timings_ct, set_timings,setup_nothing, poll_nothing},
	{ 0xFFFF, 0x000A, "BayTrail IMC","",		0, poll_fsb_ct, poll_timings_ct, set_timings,setup_nothing, poll_nothing}, // same as CedarTrail IMC

**Comment by tommybreak** [comment]
The Memory Controller is IMC(Integrated Memory Controller), the Vendor ID and Device ID can be found in the struct "struct pci_memory_controller controllers[] " in controller.c

**Comment by anphsw** [comment]
So the problem is "core imc" code is too old to support it, i dont have such hardware to test it.
You can insert debug prints and watch which values controller is reporting.

**Comment by tommybreak** [comment]
OK, thank you a lot sincerely.

**Comment by anphsw** [comment]
Futher, get_spd_spec() code is a bit outdated and not contain DDR4 parser, so you must specify DDR4 around this construction:
 
>                                if(spd_raw[2] == 0x0b){
>                                   // We are here if DDR3 present
>

**Comment by tommybreak** [comment]
yea, 
DDR4 ought to be added  in many aspects

**Comment by tommybreak** [comment]
I print out the controller index.
the reporting value is 0x7a

**Comment by anphsw** [comment]
So, controller is detected correctly. We need to extract spd information and parse it.
Please dump SPD info from module (spd_raw array).
We need to copy ddr3 parser and modify it to fit DDR4 values, here is description of spd layout: http://www.softnology.biz/pdf/4_01_02_AnnexL-R25_SPD_for_DDR4_SDRAM_Release_3_Sep2015.pdf

**Comment by tommybreak** [comment]
cpu_id.vend_id.char_array[0] == 'G' 
cpu_id.vers.bits.family == 6
cpu_id.vers.bits.model=0x0e
cpu_id.vers.bits.extendModel=0x09

**Comment by anphsw** [comment]
Not CPUID, just spd_raw[] table....

**Comment by tommybreak** [comment]
**this is the function which is used to poll the dram frequency indicated as below:**
/**intel(R) Core(TM) i7/i5/i3-8xxx**/
static void poll_fsb_coffee_lake(void)
{
	double dramclock=0, dramratio=0, fsb=0;
	unsigned long dev0=0, mchcfg=0;
	float coef = getSNBmultiplier();
	long *ptr;
	
	fsb = ((extclock / 1000) / coef);

	/* Find dramratio */
	pci_conf_read( 0, 0, 0, 0x48, 4, &dev0);
	dev0 &= 0xFFFFC000;
	ptr=(long*)(dev0+0x5E04);
	mchcfg = *ptr & 0xFFFF;
	dramratio = 1;
	
	/* Get the clock ratio */
	switch((mchcfg >> 8) & 0x01)
	{
		case 0x0:
			dramratio = (float)(*ptr & 0x1F) * (133.34f / 100.0f);
			break;
		case 0x1:
			dramratio = (float)(*ptr & 0x1F) * (100.0f / 100.0f);	
			break;
	}
	
	// Compute RAM Frequency
	dramclock = fsb * dramratio;
	dramFreq = dramclock;

	// Print DRAM Freq
	print_cpu_line(dramclock, fsb, dramType);
}

**Comment by anphsw** [comment]
If its actually working, please make git commit.
