### ISSUE TITLE
0104 loop using USB stick

### ISSUE THREAD

**Issue by teran-mckinney** [anphsw/memtest86#13]
Tried writing out the memtest.bin and memtest.img to USB. Got a 0104 loop both times. The 5.0.1 images upstream also do the same thing.

Are these supposed to be USB bootable?

**Comment by anphsw** [comment]
Yes, that images can be booted from USB. What bootloader are you using? Grub? Syslinux? Or what tool  is used to write image to USB stick?
Here is example of syslinux/extlinux config:
```
timeout 1

serial 0 115200

SAY Default serial console options 115200n8

DEFAULT memtest

LABEL memtest
    KERNEL memtest86
    APPEND console=ttyS0,115200
```

**Comment by teran-mckinney** [comment]
I was just using `pv` (equivalent to `dd`), I guess it's not a bootable MBR-style image. I did find some 5.0.1 bootable images and have ran with that. Working fine so far, although looks like your fork is more updated.
