### ISSUE TITLE
Memtest86+ 5.31b released

### ISSUE THREAD

**Issue by malvarenga123** [anphsw/memtest86#16]
Hello, I don't know if you are aware, but a beta version has been released recently. It might be interesting to merge the new version with your fixes.
http://www.memtest.org/download/5.31b/memtest86+-5.31b.tar.gz

**Comment by anphsw** [comment]
I compared 5.01 and 5.31b versions and it seems like it contains only cosmetic code fixes (and some, but incomplete, dmi code updates). Let's wait for more complex changes or feedback from original author.
