### ISSUE TITLE
the problem of booting from U-Disk

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#17]
when the memory size of my compiled binary file,mt86plus, is bigger than 279KB,  the program will not run normally ,and the SCREEN is black .
why? how could i fix the issue?

**Comment by anphsw** [comment]
What compile option caused such size? Original size is about 200k.
How you load memtest binary from u-disk? Which bootloader do you use?

**Comment by tommybreak** [comment]
I  repalce the O0 with O1, then the size is bigger than 279KB. I use USB auto installer tool " Memtest86+ USB Installer.exe" to load my memtest binary from my u-disk. the version of Memtest86+ USB Installer.exe  is v5.01.

**Comment by anphsw** [comment]
This is a problem of your compiler.
I just replaced O0 with O1 and result is 160k instead 190k with -O0.
You can test built binariers with qemu: "qemu-system-i386 -enable-kvm -fda memtest.bin -smp 2 -m 256" to exclude USB installer fault.
Please make sure that your compiler is generating correct code.

**Comment by tommybreak** [comment]
what's your gcc version?
my original shell code is as below:
memtest.bin: memtest_shared.bin bootsect.o setup.o memtest.bin.lds
	$(LD) -T memtest.bin.lds bootsect.o setup.o -b binary \
	memtest_shared.bin -o memtest.bin

when i try to build binaries with qemu:
memtest.bin: memtest_shared.bin bootsect.o setup.o memtest.bin.lds
	$(LD) -T memtest.bin.lds bootsect.o setup.o -b binary \
	memtest_shared.bin -qemu-system-i386 -enable-kvm -fda -o memtest.bin -smp 2 -m 256

the error is reported as follows:
ld: unrecognised emulation mode: 256
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
Makefile:58: recipe for target 'memtest.bin' failed
make: *** [memtest.bin] Error 1

**Comment by tommybreak** [comment]
I reckon that the USB auto installer tool " Memtest86+ USB Installer.exe" puts limitation to the size of memtest.bin. my friends also tell me that his memtest.bin cannot be booted if its size became bigger to some degree when more and more source code was added into the whole project.

**Comment by anphsw** [comment]
> $(LD) -T memtest.bin.lds bootsect.o setup.o -b binary 
> memtest_shared.bin -qemu-system-i386 -enable-kvm -fda -o memtest.bin -smp 2 -m 256

I mentioned qemu command line for checking memtest binary, this is not LD options!

> I reckon that the USB auto installer tool " Memtest86+ USB Installer.exe" puts limitation to the size of memtest.bin

Ok, we found this is not memtest problem.
As there is no source for this USB tool, we cannot check what is wrong.
Please use GRUB or SYSLINUX bootloaders for booting memtest.
