### ISSUE TITLE
smp, reliability, non-existent memory, heat, duration, test list

### ISSUE THREAD

**Issue by JumperFreeC** [anphsw/memtest86#19]
hi ! thanks for your work.

my config is r7 2700X + strix x370-f + f4-3600c15d-gtz. it runs at 3333mhz and it hold 25hrs of prime95 v298.b6 large fft (win10 latest update). while testing 5.31b, ambiant temp were pretty low (23°c max), 5.01 were running at higher temp.

bug report : entering a test list run the next test instead. if i enter 7,9 it run test#8 and #10 (that bug was already there in 5.01).
5.31b test 17GB of memory. actually it skip 1GB (from 3 to 4GB) and it add 1GB (from 16 to 17GB). 

as you explain : "There are some systems that cause Memtest86+ to be confused about the size of memory and it will try to test non-existent memory.  This will cause a large number of consecutive addresses to be reported as bad and generally there
will be many bits in error.  If you have a relatively small number of failing addresses and only one or two bits in error you can be certain that the errors are valid.  Also intermittent errors are always valid."
when selecting smp (f2) and entering a test list (T#7,T#9), i get that "large number with many bits" of errors during T#7 (200-400E), but T#9 get no error (12 pass), 
whereas when running the same loop on memtest86+ v5.01 i get an average of 1error/GB during t#9 (one bit in error - 12 pass) and no error during t#7 !
imho this is a huge improvement for T#9. whereas for t#7, before, my hardware wasn't confusing 5.01.

i have also to mention that smp enabled heat a lot more. i've noticed a higher power consumption (300w, p95 is around 200w) which obviously push my sticks to their temp limit. so i also tried to set all fans (cpu, aux, dram) at full speed before running 5.01 smp enabled. result was -96% of error. i had 2errors/12pass during t#9 which look like intermittent errors ? however i felt like 5.01 wasn't fully applying that full fans speed settings from bios. 
another thing that is true for 5.01 and 5.31b, according to the test duration, i've noticed two kind of test of the same test#. on my configuration, T#9 can be fast (2min) or slow (6min). i don't know if it's a ryzen stuff but the fact is if it finds errors, it's exclusively during slow pass. example : i had a run where it first ran 7 fast pass of T#9, then, it started to run slow pass. during the 8th slow pass, it found one error, only one bad bit, the 4th bit was +8 digit. i tried to run it with a large fft, it failed in less than 1 min (unstable set of settings @3400mhz). 
one last thing, v5.01 (smp disabled) does not find error during test list #6-7-9-10 (7 pass - 10hrs). i haven't tried it on 5.31b, but i believe it can not be different.

sorry to ask but i really wonder if i'm right to conclude that smp enabled is more like a memory controller and dram stability test, whereas smp disabled is a dram failure test ?
please could you give informations about F3 key ? that mode looks less stressing that F2, but is it reliable ?
memory sticks can be very sensitive to heat. mine doesn't like more than 42°c (thaiphoon - hwinfo). should i believe that unconsistant or small number of errors come from system overall heat ?

Thanks.

**Comment by anphsw** [comment]
> bug report : entering a test list run the next test instead. if i enter 7,9 it run test#8 and #10 (that bug was already there in 5.01).
This bug already fixed in this fork. I checked it again right now. Are you referring 5.31b? 5.31b is vanilla memtest86, I don't know why original author changed version, but not changed anything else. So please use released version of memtest86 for test.

> 5.31b test 17GB of memory. actually it skip 1GB (from 3 to 4GB) and it add 1GB (from 16 to 17GB).
Please test this with my fork, not vanilla, you can download it in releases page.

> when selecting smp (f2) and entering a test list (T#7,T#9), i get that "large number with many bits" of errors during T#7 (200-400E), but T#9 get no error (12 pass),
Vanilla versions of memtest86 contain bug in this tests, I don't know, will it be fixed or not.

Please download bianry from here: https://github.com/anphsw/memtest86/releases and reopen again if you will find any bugs.
