### ISSUE TITLE
the problem on reading bytes of ddr4 SPD 

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#20]
Hi, my closely friend.
    At present, I am trying to running your program on ASUS Z390-A(i7-9700k) whose deviceId is 0xa323 of the smbus controller. 
the issue is that the abtained spd byte,spd_raw[2],is 0x00, which leads to "ddr4 spd cannot be uncovered" .

**Comment by anphsw** [comment]
Is there only one byte set to 0x00, or whole array?
Please check SPD dump and check are other bytes correct or not?
