### ISSUE TITLE
an inssue found by 

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#8]
a DRAM defect was found by  Test 9 [Modulo 20, Random pattern] belonged to memtest86-purchase ,however,the defect cannot be found by memtest86plus. why?

**Comment by anphsw** [comment]
Can you give more details? Is the address of defect constant, or changes within some range?
What is your GCC version, or you running precompiled binary?
What is your hardware configuraton, etc...

**Comment by tommybreak** [comment]
yes,the defect address is constant ,0x8227f8
my gcc version is 5.4.0
my CPU is i5, 6 processors,  ddr3 sdram is 12GB

**Comment by anphsw** [comment]
Are you using internal graphics or external GPU?
If internal graphics enabled, this address may belong to screen buffer, so contents of this memory block is changed at every screen refresh.
BIOS must reserve(or shadow) graphics memory space so others (like memtest) will not access it, maybe bios update will also solve problem.
In case of internal graphics there is only way to avoid printing errors is exclude this memory range from testing. In case external graphics (internal must be completely shutdown in bios setup) there is almost 100% dram defect.

**Comment by tommybreak** [comment]
thank you a lot!
Now, another defect was found by Test 11 [Random number sequence, 64-bit] belonged to memtest86-pro-v7.1,however, the open-source memtest86plus-5.01 does not include Test 11 [Random number sequence, 64-bit] . Therefore, do you have any suggestion to realise the pattern in order to diagnose the defect memory cell.

**Comment by anphsw** [comment]
Another question: how long you run memtest86+?
First pass skips some long tests to show most common errors (so you don't have to need a lot of time to detect for example, some overclocking errors)
Second pass runs all tests, so some errors will be revealed only on second pass.
about tests included in memtest86pro: I don't know how this tests is written in code, and them may be subject to copyright (or not).
If you have any particual information about such tests (and this information not proprietary or subject to copyright) let me know.
