### ISSUE TITLE
the problem of test.c

### ISSUE THREAD

**Issue by tommybreak** [anphsw/memtest86#9]
in the test.c , the function ,"void movinvr(int me)", the assembly codes(started from line 386) cannot be replaced by the c codes displayed above(started from line 380) ,why?
when i try to replace the assembly code with c code, the memtest.bin will make the running system reboot.

**Comment by tommybreak** [comment]
**line 380 is here**    /* Original C code replaced with hand tuned assembly code */
                /*
			for (; p <= pe; p++) {
				*p = rand_32bits(me);
			}
*/ 
**line 386 is here**        asm __volatile__ (
                    "jmp L200\n\t"
                    ".p2align 4,,7\n\t"
                    "L201:\n\t"
                    "addl $4,%%edi\n\t"
                    "L200:\n\t"
					"pushl %%ecx\n\t" \
                    "call rand_32bits\n\t"
					"popl %%ecx\n\t" \
					"movl %%eax,(%%edi)\n\t"
                    "cmpl %%ebx,%%edi\n\t"
                    "jb L201\n\t"
                    : : "D" (p), "b" (pe), "c" (me)
					: "eax"
            );

**Comment by anphsw** [comment]
Original code was written for very old GCC version (and not by me), and you compiling on the modern version of GCC, which may optimize code and can give incorrect results.
You can compile test.c with assembler output: in makefile add "-S" option:
$(CC) -S -c -Wall -march=i486 -m32 -O0 -fomit-frame-pointer -fno-builtin -ffreestanding -fno-pie -fno-stack-protector -std=gnu99 test.c

Compile will fail, but will produce test.s file with assembler source. You can compare then assembler results of original C code optimized by GCC and hand-tuned code.

Second, if you remove all assembly code from test.c, you can compile it without "-fno-pie -fno-stack-protector" options (as they added to support modern GCC versions) and see if it works.

**Comment by tommybreak** [comment]
thanks a lot.
I have fix the problem.
the replaced c code should be as below:
/* Original C code replaced with hand tuned assembly code */
			*p = rand_32bits(me);
			for (; p < pe; ) {
				p++;
				*p = rand_32bits(me);
			}

**Comment by tommybreak** [comment]
the above c code could replace the assembly code 
my  GCC version is 5.4.0  on ubuntu 16.04

**Comment by anphsw** [comment]
Yes, it makes sense.
This code is unused, but if you will make commit fixing it, I will merge it. Or I can make it by myself, as you wish.
